name: Test AWS OIDC

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '30 5,17 * * *'

permissions:
  id-token: write
  contents: read

jobs:
  test-aws:
    if: github.repository == 'jake1331982/codepipeline'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::025066267125:role/github-token-sts
          aws-region: us-east-1

  saludo:
    runs-on: ubuntu-latest
    needs: test-aws
    steps:
      - name: Saludo y gracias
        run: echo "hola"
